#!/usr/bin/env bash
# This script send ICMP message to the IP
#+ address passed as argument to the program

if [ "$#" -eq 1 ]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
