#!/usr/bin/env bash
#This is bash script displaying "Best school" and + "hi"
#+ on the 9th iteration

index=1

while [ "$index" -le 10 ]
do
	if [ "$index" -eq 9 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	(( index++ ))
done
