#!/usr/bin/env bash
#This script display "bad luck" for 4th iteration, "good luck" for 8th iteration
#+ and "Best school" for the rest iteration

i=1
while [ "$i" -le 10 ]
do
	if (( "$i" == 4 ))
	then
		echo "bad luck"
	elif (( "$i" == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
